language: cpp
#sudo: required
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    #- clang-3.8
    - libboost1.55-all-dev
compiler:
  - gcc
  #- clang
install:
  - export CXX="g++-4.8" CC="gcc-4.8";
script:
  - mkdir build && cd build && cmake -DBoost_USE_STATIC_LIBS=OFF .. && make && cd ..
  - cd bin && ../build/tests/unittest

notifications:
  irc:
    channels:
      - irc.ircnet.ee#ircmud
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    on_success: change
    on_failure: always