language: cpp
#sudo: required
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    #- clang-3.8
    #- libboost1.55-all-dev
compiler:
  - gcc
  #- clang
install:
  - export CXX="gcc++-4.8" CC="gcc-4.8";
script: cmake -DBoost_USE_STATIC_LIBS=OFF . && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change