language: cpp
#sudo: required
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
compiler:
  - gcc
#  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
script: cmake . && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change