language: cpp
#sudo: required
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    #- gcc-4.6
    #- g++-4.6
    - clang-3.8
    - libboost1.55-all-dev
compiler:
  #- gcc
  - clang
#install:
  #- export CXX="clang++-3.8" CC="clang-3.8";
script: cmake . && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change