language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.59-all-dev
compiler:
  - gcc
#  - clang
script: cmake . && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change