language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
compiler:
  - gcc
#  - clang
script: cmake && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change