language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev 
  - sudo apt-get install qt5-qmake
compiler:
  - gcc
#  - clang
script: qmake && make

notifications:
  irc:
    channels:
      - "irc.ircnet.ee#ircmud"
    on_success: always
    on_failure: change